In [9]:
import numpy as np

temps = np.array([32, 33, 35, 31, 30, 29, 28, 33, 36, 34])

fahrenheit = (temps * 9/5) + 32

abnormal = temps[(temps < 30) | (temps > 35)]

print("Temps:", temps)
print("Fahrenheit:", fahrenheit)
print("Abnormal:", abnormal)

Temps: [32 33 35 31 30 29 28 33 36 34]
Fahrenheit: [89.6 91.4 95.  87.8 86.  84.2 82.4 91.4 96.8 93.2]
Abnormal: [29 28 36]


In [10]:
import numpy as np

data = np.array([120, 130, 115, 140, 150, 110, 125])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std Dev:", np.std(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 127.14285714285714
Median: 125.0
Std Dev: 13.05404777321219
Min: 110
Max: 150


In [11]:
import numpy as np

A = np.array([[1, 2],
             [3, 4]])

B = np.array([[5, 6],
             [7, 8]])

result = np.dot(A, B)

det = np.linalg.det(A)

print("Matrix Multiply:\n", result)
print("Determinant:", det)

Matrix Multiply:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004


In [12]:
import numpy as np

data = np.array([100, 200, 300, 400, 500])

normalized = (data - data.min()) / (data.max() - data.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [13]:
import numpy as np

dataset = np.random.randint(1, 100, size=(5, 5))

print(dataset)

[[30 78 85 25 56]
 [46 25 30 82 10]
 [26 33 15 52 87]
 [62 91 35 29 98]
 [53 22 44 43 92]]
